# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: stream pkg CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'stream/**'
      - '.github/workflows/stream.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'stream/**'
      - '.github/workflows/stream.yml'

env:
  WORKING_DIRECTORY: ./stream

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Run tests and generate coverage
      run: |
        go test ./... -coverprofile=coverage.out -covermode=atomic
      
    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.out
